### PR TITLE
fix: properly handle modules that are in an array

### LINKED ISSUE #65: semantic-release 15.9.x -> 15.10.x seem to be breaking this plugin
I'll try to take a look myself time permitting, but wanted to let you know.
Logs attached:

```
$ lerna exec --concurrency 1 -- semantic-release -e semantic-release-monorepo
lerna notice cli v3.4.3
lerna info versioning independent
lerna info Executing command in 1 package: "semantic-release -e semantic-release-monorepo"
[3:08:28 AM] [semantic-release] › ℹ  Running semantic-release version 15.10.3
[3:08:28 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[3:08:28 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[3:08:28 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[3:08:28 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[3:08:28 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[3:08:28 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[3:08:28 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[3:08:28 AM] [semantic-release] › ✔  Run automated release from branch master
[3:08:30 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[3:08:31 AM] [semantic-release] › ℹ  Found git tag @microfleet/core-v13.0.2 associated with version 13.0.2
[3:08:31 AM] [semantic-release] › ℹ  Found 9 commits since last release
[3:08:31 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: ]"
[3:08:31 AM] [semantic-release] › ✖  Failed step "analyzeCommits" of plugin "[Function: ]"
[3:08:31 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/home/runner/core/node_modules/import-from/node_modules/resolve-from/index.js:11:9)
    at module.exports (/home/runner/core/node_modules/import-from/node_modules/resolve-from/index.js:34:41)
    at module.exports (/home/runner/core/node_modules/import-from/index.js:4:49)
    at requirePlugin (/home/runner/core/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
    at resolvePluginFn (/home/runner/core/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
    at /home/runner/core/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
    at validator (/home/runner/core/node_modules/semantic-release/lib/plugins/normalize.js:30:28)
    at pReduce (/home/runner/core/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/runner/core/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }
{ TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/home/runner/core/node_modules/import-from/node_modules/resolve-from/index.js:11:9)
    at module.exports (/home/runner/core/node_modules/import-from/node_modules/resolve-from/index.js:34:41)
    at module.exports (/home/runner/core/node_modules/import-from/index.js:4:49)
    at requirePlugin (/home/runner/core/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
    at resolvePluginFn (/home/runner/core/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
    at /home/runner/core/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
    at validator (/home/runner/core/node_modules/semantic-release/lib/plugins/normalize.js:30:28)
    at pReduce (/home/runner/core/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/runner/core/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }lerna ERR! semantic-release -e semantic-release-monorepo exited 1 in '@microfleet/core'
lerna ERR! semantic-release -e semantic-release-monorepo exited 1 in '@microfleet/core'
```

### PR DESCRIPTION
**Pull request by sanpoChew**
fixes https://github.com/Updater/semantic-release-monorepo/issues/65

### CODE REVIEW

**Comment by marcguilera** [comment]
Can we merge this?

**Review by therealklanni — COMMENTED** [review]
This might be a more succinct solution.

```js
const requirePlugin = module => importFrom(process.cwd(), [].concat(module)[0]);
```

**Comment by clifford-lc** [comment]
Tested this PR locally through linked dependencies, this PR solves the issue 👍 

Though not sure about plugin name `"[Function: ]"`

`[11:34:05 am] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "[Function: ]"`

**Comment by sanpoChew** [comment]
@therealklanni changed to concat

**Comment by owenmecham** [comment]
Any word on if this fix has been validated and if it will be merged in? We're running into similar issues after upgrading semantic-release.

**Comment by egucciar** [comment]
To all invested project users,

At Updater we strive for transparency, so first we want to apologize for not giving this notice sooner as we have been figuring out how to proceed. Currently our team is focused on internal initiatives and we are no longer reviewing or maintaining these open sourced projects in the near term. This will continue until some point in the future when we can revisit these projects and determine what to do with them moving forward. 

A couple of options for those who would like to continue to use the project:

(a) Fork our project and volunteer to maintain it moving forward. If so, we will link to your fork from our README.md so other users can also use your fork for those upgrades. 
(b) Fork our project for your own use without volunteering to maintain it.
(c) Use the project as-is.

Seeing that even minor contributions come with the overhead of reviewing and testing for quality, as well as subsequently ensuring releasing those changes occurs in such a way that parties are informed whether it is a breaking or non breaking change, putting the onus on our team to confirm this manually, we are sorry to inform those in this PR that we cannot merge this for the time being and hope that you can use one of the above suggestions to keep moving forward.

Thanks,
Updater Team

**Comment by owenmecham** [comment]
@egucciar I understand your situation and appreciate the transparency. Thank you for your work thus far and for the quick response. We'll figure out a path forward.

**Comment by pmowrer** [comment]
Digging into this a little bit, it seems it is the [default configuration for the `analyze-commits` plugin that broke things](https://github.com/semantic-release/semantic-release/commit/5ba5010#diff-205c5cf625514dcf92e20a30d112c1cdR14), which as of `semantic-release` 5.10.x for some reason is defined as an array instead of as a string (and is now the only plugin with a "default").

With the addition of the plugins API in `semantic-release`, it appears the already complicated plugin system got even more complicated, adding a ton of new permutations in how plugins may be defined. It looks like this PR will definitely fix the "default" plugin issue, but it's not a general solution for handling plugins defined in an array in this way (hypothetically, a future version of `semantic-release` could define a plugin default with a an array of length > 1). 

That said, it doesn't seem worth trying to make a more generalized fix right now since. I'm going to merge this in today.

**Comment by pmowrer** [comment]
Digging into this further, the new plugin system in `semantic-release` (as of 15.10 + 15.11) actually simplifies things because it deprecates the older plugin system. I've added new utilities and create a PR against `semantic-release-monorepo` later on today

**Comment by mc0** [comment]
@pmowrer Thank you for your work! I was able to get the latest semantic-release-monorepo working as long as the array of plugins are just strings. This bug looks to be what I'm experiencing with having plugins that have more complex configuration breaking (like [this](https://github.com/semantic-release/commit-analyzer#usage)).

This appears to fix the immediate issue. Is this fix enough? If not, what else can be done?

**Comment by pmowrer** [comment]
Thanks for reporting this @mc0! Seems to be same issue as https://github.com/pmowrer/semantic-release-monorepo/issues/69#issuecomment-594312488: I missed adding support for the new plugin config syntax. Should be fixed by https://github.com/pmowrer/semantic-release-plugin-decorators/pull/23.

**Pull request closed without merging**
