### PR TITLE
Support for New Semantic Release Version and Node 18

### PR DESCRIPTION
**Pull request by w4rlock**
Please 

I need to merge theses changes.  

Theses changes resolve next error  (ERR_REQUIRED_ESM)

* Support for semantic release version
* Support for Node 18
* Fix Unit Test
* Fix Code Linters
* Tools integration for code styling (prettier, eslint)

### CODE REVIEW

**Comment by chrisEff** [comment]
@pmowrer I'd really appreciate if you could have a look at this soon, as the esm error blocks me from upgrading to semantic-release v21.

**Comment by gavmck** [comment]
@pmowrer Same issue here

**Comment by chrisEff** [comment]
@w4rlock Maybe you could focus your changes to the bare minimum of what we want to achieve here (compatibility with semantic v21 + node 18) and leave out all the rest (eslint/prettier stuff, moving from yarn to npm, etc.), so this becomes easier to review...

**Comment by nass59** [comment]
Hi, any updates?

**Comment by marklai1998** [comment]
Hi, any updates?

**Pull request closed without merging**
